# Generated by Django 3.2.7 on 2022-12-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_created=True)),
                ('image_path', models.CharField(max_length=100)),
                ('pred', models.CharField(max_length=100)),
            ],
        ),
    ]
