# Generated by Django 3.2.7 on 2022-12-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecls',
            name='time',
        ),
        migrations.AlterField(
            model_name='imagecls',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
